name: interactivesso_datatypes
description: A starting point for Dart libraries or applications.
version: 0.0.8
# homepage: https://www.example.com
repository: https://github.com/InteractivePlus/interactivesso_datatypes

environment:
  sdk: '>=2.15.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  lints: ^1.0.1
  test: ^1.20.1
dependencies: 
  country_code: ^1.0.0
  crypto: ^3.0.1
  http: ^0.13.4
  interactiveplus_shared_dart: ^0.0.11
  json_annotation: ^4.4.0
  phone_numbers_parser: ^4.2.0
